"""Context revision models for Google OmniMemory.

Tracks semantic delta revisions generated by the Memory Agent using
Google Diff-Match-Patch algorithms, preventing prompt duplication.
"""

from __future__ import annotations
import uuid
import time
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class DiffOperation(BaseModel):
    """An atomic text change operation from Google Diff-Match-Patch (EQUAL, INSERT, DELETE)."""
    op: int  # 0: EQUAL, 1: INSERT, -1: DELETE
    text: str


class ContextRevision(BaseModel):
    """A semantic revision of the active agent context.
    
    Instead of concatenating new thoughts to the prompt, the Memory Agent
    uses Google Diff-Match-Patch to apply updates in-place or generate
    a consolidated state delta.
    """
    revision_id: str = Field(default_factory=lambda: f"rev_{uuid.uuid4().hex[:8]}")
    session_id: str
    step_start: int
    step_end: int
    timestamp: float = Field(default_factory=time.time)
    
    # State evolution:
    previous_context_summary: str
    revised_context_summary: str
    patch_delta: str                   # Textual patch representation from diff-match-patch
    diff_operations: List[DiffOperation] = Field(default_factory=list)
    
    # Economics:
    raw_step_tokens: int               # Sum of intermediate steps consumed
    revised_tokens: int                # Compact revised context token size
    compression_ratio: float = 1.0     # raw_step_tokens / revised_tokens
    
    # Extracted facts and goals:
    active_goals: List[str] = Field(default_factory=list)
    resolved_goals: List[str] = Field(default_factory=list)
    key_constraints: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
